### ISSUE TITLE
Can't connect to the server

### ISSUE THREAD

**Issue by dennee** [mattermost/mattermost-plugin-calls#136]
Hello! I installed a new version of the Mattermost Server 7.0.1 Team Edition and Calls Plugin 0.6.1

I wanted to test drive the Mattermost calls, but the desktop client can't connect to the server.

## Infrastructure

I deployed the docker version of the Mattermost Server on the dedicated server. I've attached the component diagram that is illustrated the deployment.
![image](https://user-images.githubusercontent.com/14939117/176886240-545b69a4-1bdd-4447-8a96-c795a75c13de.png)

The desktop client connects to the server via 443 port. The 8884 port is used for the calls connection.

The nginx processes HTTPS and WSS connections and proxies to the docker container with the Mattermost Server. This part works well.

The iptables routes all UDP traffic for the 8884 port to the docker container.

I hope I've explained it clearly :)

## Subject

When I push the "Start Call" button my teammates can join to the call but nobody hear nobody and call members disconnect after 45 seconds.
The developer console logs are below
```stacktrace
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: a/v device change detected
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: found default audio input device to use: Default
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: found default audio output device to use: Default
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: a/v device change detected
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 [Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)
bo @ com.mattermost.calls_e71c72812e3ae94d_bundle.js:2
initVAD @ com.mattermost.calls_e71c72812e3ae94d_bundle.js:2
init @ com.mattermost.calls_e71c72812e3ae94d_bundle.js:2
await in init (async)
o @ com.mattermost.calls_e71c72812e3ae94d_bundle.js:2
(anonymous) @ com.mattermost.calls_e71c72812e3ae94d_bundle.js:2
a @ call_button.tsxx:56
s @ react-dom.production.min.jss:14
c @ react-dom.production.min.jss:14
(anonymous) @ react-dom.production.min.jss:14
F @ react-dom.production.min.jss:15
ot @ react-dom.production.min.jss:52
at @ react-dom.production.min.jss:51
rt @ react-dom.production.min.jss:52
mt @ react-dom.production.min.jss:56
x @ react-dom.production.min.jss:287
G @ react-dom.production.min.jss:19
Jt @ react-dom.production.min.jss:70
Zt @ react-dom.production.min.jss:69
t.unstable_runWithPriority @ scheduler.production.min.jss:19
Wi @ react-dom.production.min.jss:122
v @ react-dom.production.min.jss:287
Vt @ react-dom.production.min.jss:68
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: ws open, sending join msg
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: join ack received, initializing connection
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: local signal: {"type":"offer","sdp":"v=0\r\no=- 7506066426796797632 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:RZcX\r\na=ice-pwd:70A9VgLqA4PJ/ZZ/TAvSSTKg\r\na=ice-options:trickle\r\na=fingerprint:sha-256 1A:47:93:F4:57:54:7C:12:7A:71:EF:C7:C1:FA:5E:65:C0:B5:31:0F:07:4A:37:A0:68:EC:5E:E8:A0:38:C7:F2\r\na=setup:actpass\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n"}
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: local signal: {"type":"candidate","candidate":{"candidate":"candidate:2107020778 1 udp 2122260223 172.50.254.1 41331 typ host generation 0 ufrag RZcX network-id 1","sdpMLineIndex":0,"sdpMid":"0"}}
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: local signal: {"type":"candidate","candidate":{"candidate":"candidate:3885250869 1 udp 2122194687 172.17.0.1 52258 typ host generation 0 ufrag RZcX network-id 2","sdpMLineIndex":0,"sdpMid":"0"}}
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: local signal: {"type":"candidate","candidate":{"candidate":"candidate:1699298163 1 udp 2122129151 192.168.0.58 42658 typ host generation 0 ufrag RZcX network-id 3","sdpMLineIndex":0,"sdpMid":"0"}}
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2          PUT https://chat.insys.io/api/v4/users/7mmn7y4x9pnq985tt7c7siofec/teams/threads/f7r3e4ukoidp8qgyunxjahzchy/following 404
(anonymous) @ com.mattermost.calls_e71c72812e3ae94d_bundle.js:2
(anonymous) @ com.mattermost.calls_e71c72812e3ae94d_bundle.js:2
(anonymous) @ com.mattermost.calls_e71c72812e3ae94d_bundle.js:2
(anonymous) @ com.mattermost.calls_e71c72812e3ae94d_bundle.js:2
(anonymous) @ index.jss:8
i @ com.mattermost.calls_e71c72812e3ae94d_bundle.js:2
(anonymous) @ com.mattermost.calls_e71c72812e3ae94d_bundle.js:2
(anonymous) @ websocket_actions.jsxx:572
Me @ websocket_actions.jsxx:566
conn.e.conn.onmessage @ websocket_client.tsxx:174
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: remote signal {"type":"answer","sdp":"v=0\r\no=- 7413999486141202981 1656675804 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=fingerprint:sha-256 B0:CF:E5:C9:F1:8F:52:F8:80:B3:B7:D7:81:BA:D6:CC:F1:81:3D:6B:46:01:87:25:21:CE:57:81:A1:77:CE:BF\r\na=extmap-allow-mixed\r\na=group:BUNDLE 0\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=setup:active\r\na=mid:0\r\na=sendrecv\r\na=sctp-port:5000\r\na=ice-ufrag:zjDgUiWiGnwkPqzW\r\na=ice-pwd:hcCpMXyxNOOebaWwGrkmFZvKOhQGZtkr\r\n"}
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: local signal: {"type":"candidate","candidate":{"candidate":"candidate:857041178 1 tcp 1518280447 172.50.254.1 9 typ host tcptype active generation 0 ufrag RZcX network-id 1","sdpMLineIndex":0,"sdpMid":"0"}}
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: local signal: {"type":"candidate","candidate":{"candidate":"candidate:2836907461 1 tcp 1518214911 172.17.0.1 9 typ host tcptype active generation 0 ufrag RZcX network-id 2","sdpMLineIndex":0,"sdpMid":"0"}}
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: local signal: {"type":"candidate","candidate":{"candidate":"candidate:734709635 1 tcp 1518149375 192.168.0.58 9 typ host tcptype active generation 0 ufrag RZcX network-id 3","sdpMLineIndex":0,"sdpMid":"0"}}
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: remote signal {"candidate":{"candidate":"candidate:434529953 1 udp 2130706431 PUBLIC_IP 8884 typ host","sdpMid":"","sdpMLineIndex":0,"usernameFragment":null},"type":"candidate"}
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: local signal: {"type":"candidate","candidate":{"candidate":"candidate:2340875326 1 udp 1686052607 92.124.128.60 41331 typ srflx raddr 172.50.254.1 rport 41331 generation 0 ufrag RZcX network-id 1","sdpMLineIndex":0,"sdpMid":"0"}}
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: local signal: {"type":"candidate","candidate":{"candidate":"candidate:79019993 1 udp 1685987071 92.124.128.60 52258 typ srflx raddr 172.17.0.1 rport 52258 generation 0 ufrag RZcX network-id 2","sdpMLineIndex":0,"sdpMid":"0"}}
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: local signal: {"type":"candidate","candidate":{"candidate":"candidate:2472100519 1 udp 1685921535 92.124.128.60 42658 typ srflx raddr 192.168.0.58 rport 42658 generation 0 ufrag RZcX network-id 3","sdpMLineIndex":0,"sdpMid":"0"}}
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: vad: noise avg 21 58.466666666666676
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: peer error Error: Connection failed.
    at h._onConnectionStateChange (com.mattermost.calls_e71c72812e3ae94d_bundle.js:2:762049)
    at RTCPeerConnection._pc.onconnectionstatechange (com.mattermost.calls_e71c72812e3ae94d_bundle.js:2:751869)
mn @ com.mattermost.calls_e71c72812e3ae94d_bundle.js:2
(anonymous) @ com.mattermost.calls_e71c72812e3ae94d_bundle.js:2
i.emit @ com.mattermost.calls_e71c72812e3ae94d_bundle.js:2
(anonymous) @ com.mattermost.calls_e71c72812e3ae94d_bundle.js:2
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: disconnect
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: ws close: 1005
```

The calls plugin settings
![image](https://user-images.githubusercontent.com/14939117/176888642-74179b82-e476-4072-98ef-91428b65f77c.png)

The nmap command result
```stacktrace
Host is up (0.076s latency).

PORT     STATE         SERVICE
8884/udp open|filtered unknown

Nmap done: 1 IP address (1 host up) scanned in 1.03 seconds
```

The netcat command result
```
netcat -z -v -u PUBLIC_IP 8884
Connection to PUBLIC_IP 8884 port [udp/*] succeeded!
```

Looks like the webapp can't connect to the server part of the plugin

## Plugin Code Analysis

I tried to found answers my questions in the plugin source code. 

I've found that the plugin use the [mattermost/rtcd](https://github.com/mattermost/rtcd) module. I've looked at the `Start()` function in the `server.go` file.
I've analyze this part of code
![image](https://user-images.githubusercontent.com/14939117/176890106-ba9a9502-8806-4dba-b6a2-12f67863ddaf.png)

I see that the `getPublicIP` function return the my server public IP if the ICE host override isn't set. After this the RTC server starts listen the server public IP and the ICE Port UDP.

For example, my public IP is `1.2.3.4` and the RTC server listen the `1.2.3.4:8884`.

As i mentioned earlier, the mattermost server is launched in the docker container. The docker container hasn't network interface that provides the `1.2.3.4` IP address. The container has the next network interfaces
```
eth0      Link encap:Ethernet  HWaddr 02:42:AC:32:00:02  
          inet addr:172.50.0.2  Bcast:172.50.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5964789 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5250916 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:3039726993 (2.8 GiB)  TX bytes:1586327453 (1.4 GiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:69394 errors:0 dropped:0 overruns:0 frame:0
          TX packets:69394 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:6604609 (6.2 MiB)  TX bytes:6604609 (6.2 MiB)
```

I guess that the calls plugin server should listen the `0.0.0.0` if it run in the docker. 
I tried to set the ICE Host override as `0.0.0.0` but the webapp part of the plugin starts to send request to the `0.0.0.0:8884`.

Can you help me?

**Comment by streamer45** [comment]
@dennee 

To confirm, is the PUBLIC_IP here:

```
com.mattermost.calls_e71c72812e3ae94d_bundle.js:2 com.mattermost.calls: remote signal {"candidate":{"candidate":"candidate:434529953 1 udp 2130706431 PUBLIC_IP 8884 typ host","sdpMid":"","sdpMLineIndex":0,"usernameFragment":null},"type":"candidate"}
```

the same one you tested with netcat? Does sending data from client through UDP 8884 to that host actually reach the MM container? It feels like everything is setup correctly but for the call to fail that way something must be blocked in between.

**Comment by streamer45** [comment]
Also, to clarify: the public IP is only discovered so that it get be returned to clients. The plugin will always listen on the available local interface:

https://github.com/mattermost/rtcd/blob/a366a489a001bf02a4066bc3d92b0507c772290d/service/rtc/server.go#L114

Of course what's important to make things work is that there's a path from clients through the public IP up to that local interface so that data can be transmitted.

**Comment by dennee** [comment]
Morning, @streamer45! Thanks for answer

> To confirm, is the PUBLIC_IP here: the same one you tested with netcat?

yeah, that's the same

> Of course what's important to make things work is that there's a path from clients through the public IP up to that local interface so that data can be transmitted.

I've checked this out

## My steps

1. I executed the next command to open the shell inside the mattermost docker container
```shell
docker exec -it mattermost sh
```
2. I disabled the calls plugin and call the `nc` command in listen mode
```shell
nc -l -u 0.0.0.0 8884
```
3. I create the file `hello_world` in the home directory on the **host** machine. The file content is below
```plain
hello
world
```

4. I call the `nc` command
```shell
cat hello_world | nc -u localhost 8884
```

5. Check the console output in the docker container
```shell
~ $ nc -l -u 0.0.0.0 8884
hello
world
```

6. Stop the listen command in the docker container and run again

7. I created the same file on the my PC 
```plain
hello
mattermost
```

8. and call `nc` command
```shell
cat hello_world | nc -u PUBLIC_IP 8884
```

7. Check the console output in the docker container
```shell
~ $ nc -l -u 0.0.0.0 8884
hello
mattermost
```

8. Try to send response from the server to the client. Write the "hi" word in the server console
```shell
~ $ nc -l -u 0.0.0.0 8884
hello
mattermost
hi
```

9. Look at the client console
```shell
~$ cat hello_world | nc -u PUBLIC_IP 8884
hi
```

Conclusion: The remote connection works

I attached the plugin logs from the server that were logged during calls attempts
```
{"timestamp":"2022-07-02 04:31:49.519 Z","level":"debug","msg":"handleJoin","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleJoin websocket.go:334","userID":"USER_ID","connID":"t1c4ngwgnbnju8ewreftyodche","channelID":"CHANNEL_ID"}
{"timestamp":"2022-07-02 04:31:49.545 Z","level":"debug","msg":"got handlerID","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleJoin websocket.go:403","handlerID":""}
{"timestamp":"2022-07-02 04:31:49.546 Z","level":"debug","msg":"initializing RTC session","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleJoin.func2 websocket.go:435","userID":"USER_ID","connID":"t1c4ngwgnbnju8ewreftyodche","channelID":"CHANNEL_ID"}
{"timestamp":"2022-07-02 04:31:49.960 Z","level":"debug","msg":"candidate!","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleClientMsg websocket.go:136"}
{"timestamp":"2022-07-02 04:31:49.960 Z","level":"debug","msg":"candidate!","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleClientMsg websocket.go:136"}
{"timestamp":"2022-07-02 04:31:49.960 Z","level":"debug","msg":"setting ICE candidate for remote","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80"}
{"timestamp":"2022-07-02 04:31:49.961 Z","level":"debug","msg":"setting ICE candidate for remote","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80"}
{"timestamp":"2022-07-02 04:31:50.057 Z","level":"debug","msg":"candidate!","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleClientMsg websocket.go:136"}
{"timestamp":"2022-07-02 04:31:50.058 Z","level":"debug","msg":"setting ICE candidate for remote","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80"}
{"timestamp":"2022-07-02 04:31:50.058 Z","level":"debug","msg":"candidate!","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleClientMsg websocket.go:136"}
{"timestamp":"2022-07-02 04:31:50.059 Z","level":"debug","msg":"setting ICE candidate for remote","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80"}
{"timestamp":"2022-07-02 04:31:50.144 Z","level":"debug","msg":"candidate!","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleClientMsg websocket.go:136"}
{"timestamp":"2022-07-02 04:31:50.145 Z","level":"debug","msg":"setting ICE candidate for remote","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80"}
{"timestamp":"2022-07-02 04:31:54.958 Z","level":"debug","msg":"ice gathering complete","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80"}
{"timestamp":"2022-07-02 04:31:56.349 Z","level":"debug","msg":"ice disconnected","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80","sessionID":"t1c4ngwgnbnju8ewreftyodche"}
{"timestamp":"2022-07-02 04:31:56.349 Z","level":"debug","msg":"peer connection disconnected","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80","sessionID":"t1c4ngwgnbnju8ewreftyodche"}
{"timestamp":"2022-07-02 04:32:06.499 Z","level":"debug","msg":"closing channel for session","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).OnWebSocketDisconnect.func1 websocket.go:271","userID":"USER_ID","connID":"t1c4ngwgnbnju8ewreftyodche","channelID":"CHANNEL_ID"}
{"timestamp":"2022-07-02 04:32:06.500 Z","level":"debug","msg":"done","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleJoin websocket.go:462","userID":"USER_ID","connID":"t1c4ngwgnbnju8ewreftyodche","channelID":"CHANNEL_ID"}
{"timestamp":"2022-07-02 04:32:06.502 Z","level":"debug","msg":"ice closed","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80","sessionID":"t1c4ngwgnbnju8ewreftyodche"}
{"timestamp":"2022-07-02 04:32:06.502 Z","level":"debug","msg":"peer connection closed","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80","sessionID":"t1c4ngwgnbnju8ewreftyodche"}
{"timestamp":"2022-07-02 04:32:06.503 Z","level":"debug","msg":"removing session from state","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleJoin websocket.go:486","userID":"USER_ID"}
{"timestamp":"2022-07-02 04:32:06.519 Z","level":"debug","msg":"done, removing session","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).OnWebSocketDisconnect.func1 websocket.go:274","userID":"USER_ID","connID":"t1c4ngwgnbnju8ewreftyodche","channelID":"CHANNEL_ID"}
```

The full server log that was logged during calls attempts
```
{"timestamp":"2022-07-02 04:50:23.485 Z","level":"debug","msg":"handleJoin","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleJoin websocket.go:334","userID":"USER_ID","connID":"b48p6hsseb8ozceuieg5fy7hjy","channelID":"CHANNEL_ID"}
{"timestamp":"2022-07-02 04:50:23.514 Z","level":"debug","msg":"got handlerID","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleJoin websocket.go:403","handlerID":""}
{"timestamp":"2022-07-02 04:50:23.515 Z","level":"debug","msg":"initializing RTC session","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleJoin.func2 websocket.go:435","userID":"USER_ID","connID":"b48p6hsseb8ozceuieg5fy7hjy","channelID":"CHANNEL_ID"}
{"timestamp":"2022-07-02 04:50:23.993 Z","level":"debug","msg":"not found handler triggered","caller":"web/web.go:63","path":"/api/v4/users/USER_ID/teams/threads/oywwa3nwmfgad8zup9n85otu6e/following","code":404,"ip":"MY_PC_IP"}
{"timestamp":"2022-07-02 04:50:24.012 Z","level":"debug","msg":"candidate!","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleClientMsg websocket.go:136"}
{"timestamp":"2022-07-02 04:50:24.013 Z","level":"debug","msg":"setting ICE candidate for remote","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80"}
{"timestamp":"2022-07-02 04:50:24.013 Z","level":"debug","msg":"candidate!","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleClientMsg websocket.go:136"}
{"timestamp":"2022-07-02 04:50:24.014 Z","level":"debug","msg":"setting ICE candidate for remote","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80"}
{"timestamp":"2022-07-02 04:50:24.119 Z","level":"debug","msg":"candidate!","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleClientMsg websocket.go:136"}
{"timestamp":"2022-07-02 04:50:24.119 Z","level":"debug","msg":"setting ICE candidate for remote","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80"}
{"timestamp":"2022-07-02 04:50:24.120 Z","level":"debug","msg":"candidate!","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleClientMsg websocket.go:136"}
{"timestamp":"2022-07-02 04:50:24.121 Z","level":"debug","msg":"setting ICE candidate for remote","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80"}
{"timestamp":"2022-07-02 04:50:24.200 Z","level":"debug","msg":"candidate!","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleClientMsg websocket.go:136"}
{"timestamp":"2022-07-02 04:50:24.201 Z","level":"debug","msg":"setting ICE candidate for remote","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80"}
{"timestamp":"2022-07-02 04:50:29.245 Z","level":"debug","msg":"ice gathering complete","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80"}
{"timestamp":"2022-07-02 04:50:30.405 Z","level":"debug","msg":"ice disconnected","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80","sessionID":"b48p6hsseb8ozceuieg5fy7hjy"}
{"timestamp":"2022-07-02 04:50:30.406 Z","level":"debug","msg":"peer connection disconnected","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80","sessionID":"b48p6hsseb8ozceuieg5fy7hjy"}
{"timestamp":"2022-07-02 04:50:31.375 Z","level":"debug","msg":"Websocket request","caller":"wsapi/websocket_handler.go:25","action":"user_update_active_status"}
{"timestamp":"2022-07-02 04:50:37.452 Z","level":"debug","msg":"Websocket request","caller":"wsapi/websocket_handler.go:25","action":"user_update_active_status"}
{"timestamp":"2022-07-02 04:50:39.337 Z","level":"debug","msg":"websocket.NextReader: client side closed socket","caller":"app/web_conn.go:828","user_id":"USER_ID"}
{"timestamp":"2022-07-02 04:50:39.337 Z","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:156","method":"GET","url":"/api/v4/websocket","request_id":"o34iuijo4igmuec5wdtyq93fye"}
{"timestamp":"2022-07-02 04:50:39.339 Z","level":"debug","msg":"closing channel for session","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).OnWebSocketDisconnect.func1 websocket.go:271","userID":"USER_ID","connID":"b48p6hsseb8ozceuieg5fy7hjy","channelID":"CHANNEL_ID"}
{"timestamp":"2022-07-02 04:50:39.339 Z","level":"debug","msg":"done","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleJoin websocket.go:462","userID":"USER_ID","connID":"b48p6hsseb8ozceuieg5fy7hjy","channelID":"CHANNEL_ID"}
{"timestamp":"2022-07-02 04:50:39.342 Z","level":"debug","msg":"ice closed","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80","sessionID":"b48p6hsseb8ozceuieg5fy7hjy"}
{"timestamp":"2022-07-02 04:50:39.342 Z","level":"debug","msg":"peer connection closed","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80","sessionID":"b48p6hsseb8ozceuieg5fy7hjy"}
{"timestamp":"2022-07-02 04:50:39.342 Z","level":"debug","msg":"removing session from state","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleJoin websocket.go:486","userID":"USER_ID"}
{"timestamp":"2022-07-02 04:50:39.360 Z","level":"debug","msg":"done, removing session","caller":"app/plugin_api.go:934","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).OnWebSocketDisconnect.func1 websocket.go:274","userID":"USER_ID","connID":"b48p6hsseb8ozceuieg5fy7hjy","channelID":"CHANNEL_ID"}
{"timestamp":"2022-07-02 04:50:39.742 Z","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:156","method":"GET","url":"/api/v4/channels/CHANNEL_ID/stats","request_id":"yskbsmxyqbydjpd9bzbhpkikje","status_code":"200"}
{"timestamp":"2022-07-02 04:50:39.744 Z","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:156","method":"POST","url":"/api/v4/channels/members/me/view","request_id":"zqbshw5n6tdxiy54now87mi3qw","status_code":"200"}
{"timestamp":"2022-07-02 04:50:39.761 Z","level":"info","msg":"Notification will be sent","caller":"app/notification_push.go:411","logSource":"notifications","ackId":"drni3f8ptfr688ka8wyghbrquw","type":"clear","userId":"USER_ID","postId":"","status":"Prepared to send"}
{"timestamp":"2022-07-02 04:50:40.259 Z","level":"info","msg":"Notification sent","caller":"app/notification_push.go:121","logSource":"notifications","ackId":"drni3f8ptfr688ka8wyghbrquw","type":"clear","userId":"USER_ID","postId":"","channelId":"CHANNEL_ID","deviceId":"DEVICE_ID","status":"Successful"}
{"timestamp":"2022-07-02 04:50:40.396 Z","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:156","method":"POST","url":"/api/v4/channels/members/me/view","request_id":"s5bi3acybpbp5eea53s5j571qr","status_code":"200"}
```

**Comment by streamer45** [comment]
Thanks @dennee. Indeed it looks like everything is supposed to work just fine. A couple of things to check further:

- Have you tried connecting from a browser instead of the Desktop client and see if the same problem occurs?
- Temporarily running the MM server with `PION_LOG_TRACE=ice` environment var set should output all sorts of low level information about the underlying connection attempts when establishing a call. Having that should give us more clues on what's failing exactly.

On a separate note, please feel free to reach out internally on our [community server](https://community.mattermost.com) if you prefer to share logs privately. You can find me as `@claudio.costa`.

**Comment by dennee** [comment]
> Have you tried connecting from a browser instead of the Desktop client and see if the same problem occurs?

Yeah, I've tried to call via Mozilla Firefox 101.0.1 and have caught the same problem

> Temporarily running the MM server with PION_LOG_TRACE=ice environment var set should output all sorts of low level information about the underlying connection attempts when establishing a call. Having that should give us more clues on what's failing exactly.

I've left logs in the direct messages

**Comment by streamer45** [comment]
This was solved internally I believe, closing now.
