### ISSUE TITLE
Calls crashed

### ISSUE THREAD

**Issue by redfoxlee** [mattermost/mattermost-plugin-calls#504]
Hi, we have experienced plugin process crashing this morning.

Here's the logs:
```bash
"error [2023-08-27 23:54:22.826 Z] Plugin failed to ServeHTTP, RPC call failed   caller=""plugin/client_rpc.go:423"" plugin_id=com.mattermost.calls error=""unexpected EOF"""
"error [2023-08-27 23:54:22.827 Z] plugin process exited                         caller=""plugin/hclog_adapter.go:79"" plugin_id=com.mattermost.calls wrapped_extras=""pathplugins/com.mattermost.calls/server/dist/plugin-linux-amd64pid2319errorexit status 2"""
"debug [2023-08-27 23:54:22.817 Z] reflect.Value.call({0xc00036af60?, 0xc00070e370?, 0x13?}, {0xfd1423, 0x4}, {0xc000ae4ef8, 0x3, 0x3?}) caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z]     reflect/value.go:584 +0x8c5                  caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z] reflect.Value.Call({0xc00036af60?, 0xc00070e370?, 0x0?}, {0xc000517ef8?, 0xc000e820a0?, 0xc000517f42?}) caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z]     reflect/value.go:368 +0xbc                   caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z] net/rpc.(*service).call(0xc0003a2400, 0xc000045500?, 0x0?, 0xc0006a00e0, 0xc0000cae00, 0xc000517f48?, {0xdec840?, 0xc0001f87c0?, 0xc000302000?}, {0xdfcb40, ...}, ...) caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z]     net/rpc/server.go:382 +0x226                 caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z] created by net/rpc.(*Server).ServeCodec       caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z]     net/rpc/server.go:479 +0x3fe                 caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z] panic: runtime error: index out of range [0] with length 0 caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z]                                               caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z] goroutine 1107175 [running]:                  caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z] main.isMobilePostGA(0xc000c44000)             caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z]     github.com/mattermost/mattermost-plugin-calls/server/utils.go:116 +0x1ed caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z] main.(*Plugin).handleGetAllChannels(0xc0001b4540, {0x1186bb8, 0xc0001d18f0}, 0xc000c44000) caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z]     github.com/mattermost/mattermost-plugin-calls/server/api.go:99 +0x7f caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z] main.(*Plugin).ServeHTTP(0xc0001b4540, 0xfc7420?, {0x1186bb8, 0xc0001d18f0}, 0xc000c44000) caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z]     github.com/mattermost/mattermost-plugin-calls/server/api.go:568 +0x398 caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z] github.com/mattermost/mattermost/server/public/plugin.(*hooksRPCServer).ServeHTTP(0xc00032f3a0, 0xc0001f87c0, 0x1?) caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
"debug [2023-08-27 23:54:22.817 Z]     github.com/mattermost/mattermost/server/public@v0.0.0-20230613002302-62a3ee8adcb5/plugin/client_rpc.go:453 +0x417 caller=""plugin/hclog_adapter.go:54"" plugin_id=com.mattermost.calls"
```
According to the logs, it seems like a bug (there's always an exception...), can you confirm that?

https://github.com/mattermost/mattermost-plugin-calls/blob/8196cd1424ec7859f4eb5cf06e9050c41d17cc5e/server/utils.go#L116

we are currently using

mattermost@v7.8
mattermost-plugin-calls@v0.18.0

Thanks!

**Comment by streamer45** [comment]
Thanks for the report @redfoxlee , sounds like some requests are missing the expected `User-Agent` HTTP header. Either way, it shouldn't crash that way. I filed a ticket ([MM-54259](https://mattermost.atlassian.net/browse/MM-54259)) and will get someone to at this soon.

**Comment by redfoxlee** [comment]
@streamer45 Thanks for the confirmation! We've experienced this couple times, Hope you guys can fix this issue ASAP.

**Comment by cpoile** [comment]
@redfoxlee A dot release of the plugin has been released with the fix: https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v0.18.1
We've also released to the marketplace, if you're able to use that. Thanks for the report!

**Comment by redfoxlee** [comment]
@cpoile Thank you so much! The plugin has been deployed in production and it looks good so far.
