### ISSUE TITLE
PC app click start no response

### ISSUE THREAD

**Issue by xiaopan369** [mattermost/mattermost-plugin-calls#77]
PC app click start no response

**Comment by streamer45** [comment]
Hi @xiaopan369 , could you provide more info on what's happening? Sharing console logs would be a great start.

**Comment by ToX82** [comment]
Hi! I'm having the same issue. Here is some console logs:

```
com.mattermost.calls_1e7361aa1e5244af_bundle.js:2 com.mattermost.calls: TypeError: Cannot read properties of null (reading 'length')
    at com.mattermost.calls_1e7361aa1e5244af_bundle.js:2:1197269
mn @ com.mattermost.calls_1e7361aa1e5244af_bundle.js:2
(anonymous) @ com.mattermost.calls_1e7361aa1e5244af_bundle.js:2
```

When I click on the "start call" button nothing seems to be happening but another console log appears

```
com.mattermost.calls_1e7361aa1e5244af_bundle.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'enumerateDevices')
    at Do.updateDevices (com.mattermost.calls_1e7361aa1e5244af_bundle.js:2:1084713)
    at Do.init (com.mattermost.calls_1e7361aa1e5244af_bundle.js:2:1084886)
    at o (com.mattermost.calls_1e7361aa1e5244af_bundle.js:2:1194460)
    at Object.action (com.mattermost.calls_1e7361aa1e5244af_bundle.js:2:1193921)
    at a (call_button.tsx:56:36)
    at Object.s (react-dom.production.min.js:14:84)
    at c (react-dom.production.min.js:14:238)
    at react-dom.production.min.js:14:292
    at F (react-dom.production.min.js:15:72)
    at ot (react-dom.production.min.js:52:170)
```

**Comment by streamer45** [comment]
@ToX82 , that error suggests you may be running your server on plain HTTP? For the plugin to work you must be running a secure HTTPs connection. This is a browser requirement as audio devices won't be available to use on unsecure websites.

**Comment by ToX82** [comment]
You are actually correct @streamer45, thanks a lot!
I think a warning message would be nice though, I would have never figured it out by myself probably :)

**Comment by streamer45** [comment]
Indeed, we need to document that and possibly return a more actionable error. I created an internal ticket ([MM-45017](https://mattermost.atlassian.net/browse/MM-45017)) for this improvement. Thanks for the feedback here :)

**Comment by vmohir** [comment]
I'm having the same error. `/call start` works but clicking on the "start" button won't work and logs this in the console:

```
react_devtools_backend.js:4026 [Util] handleError::  Uncaught TypeError: t.action is not a function
overrideMethod @ react_devtools_backend.js:4026
b @ com.github.matterpoll.matterpoll_8d4d7b4076b9ba73_bundle.js:312
N @ com.github.matterpoll.matterpoll_8d4d7b4076b9ba73_bundle.js:312
(anonymous) @ com.github.matterpoll.matterpoll_8d4d7b4076b9ba73_bundle.js:312
focalboard_c3252f522e64fa70_bundle.js:2 [Util] handleError::  Uncaught TypeError: t.action is not a function
react-dom.production.min.js:52 Uncaught TypeError: t.action is not a function
    at onClick (call_button.tsx:44:30)
    at Object.s (react-dom.production.min.js:14:84)
    at c (react-dom.production.min.js:14:238)
    at react-dom.production.min.js:14:292
    at h (react-dom.production.min.js:15:72)
    at rt (react-dom.production.min.js:52:170)
    at at (react-dom.production.min.js:51:255)
    at ot (react-dom.production.min.js:52:334)
    at ft (react-dom.production.min.js:56:10)
    at P (react-dom.production.min.js:287:189)
onClick @ call_button.tsx:44
s @ react-dom.production.min.js:14
c @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
h @ react-dom.production.min.js:15
rt @ react-dom.production.min.js:52
at @ react-dom.production.min.js:51
ot @ react-dom.production.min.js:52
ft @ react-dom.production.min.js:56
P @ react-dom.production.min.js:287
G @ react-dom.production.min.js:19
Qt @ react-dom.production.min.js:70
$t @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
qi @ react-dom.production.min.js:122
w @ react-dom.production.min.js:287
Vt @ react-dom.production.min.js:68
root.jsx:35          POST https://mattermost.pegah.tech/api/v4/logs 401
```

Also, it's not specific to the desktop app, the same error is logged in the browser

**Comment by streamer45** [comment]
@vmohir That's a different error by the looks of it. Also I don't see anything related to the Calls plugin. Could you share the whole log perhaps?

**Comment by vmohir** [comment]
This is the only thing that logs out. Also I'm using Mattermost 7 and calls 0.6.1

**Comment by streamer45** [comment]
Closing this for now as likely unrelated. Feel free to re-open as needed.
